### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by jubaedprince** [tayabsoomro/rocketship#10]
I and my colleague [Minhaz bhai] (has experience using react) tried to add react-router to the project. It didn't work properly. Our assumption is there are problems with configuration. 
The seed project that you used is about 1 year old and react has evolved much in the meantime. 
We suggest you to use https://github.com/facebookincubator/create-react-app as seed of the project and grow from there. 
Minhaz bhai prepared a project for you to look at [https://drive.google.com/open?id=0BymJEZt-DeOIUkczbU1LSkxJaXM ], you can use that or you can start from beginning. Most of your codes can be copy pasted easily in the new structure. 
The approach that you took will make your life very difficult. It is also suggested that you use yarn as dependency manager.
Hope this helps!

**Comment by mahmudazam** [comment]
We were able to shift all our code to the starter in the Google Drive link.
